apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-maxsurge-deploy
  labels:
    type: webapp
spec:
  template:
    metadata:
      name: my-maxsurge-pod
      labels:
        type: webapp
    spec:
      containers:
        - name: my-maxsurge-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
