apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-claim
spec:
  storageClassName: "mongo-ebs-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
