apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob-everyonemin
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: everyonemin-cronjob-container
              image: busybox:1.28
              command:
                - /bin/sh
                - -c
                - sleep 30
          restartPolicy: OnFailure