apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 20
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test-app
          image: nginx
          ports:
            - containerPort: 80
