apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
  - kind: Group
    name: "developer"
    # apiGroup's value will be the 1st part of apiVersion
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  # Same name as defined inside "Role" yaml
  name: developer-role
  apiGroup: rbac.authorization.k8s.io

