apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-recreate-deployment
  labels:
    type: webapp
spec:
  template:
    metadata:
      name: my-recreate-pod
      labels:
        type: webapp
    spec:
      containers:
        - name: my-recreate-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: webapp
  strategy:
    type: Recreate
