apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-without-secret-or-configmap
  labels:
    app: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
        - image: mysql
          name: mysql-container
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
